#!/usr/bin/env tsx
// Scrape video metadata from Gentry Stein's two YouTube playlists and write a
// generated TS catalog to packages/data/src/generated/trick-videos.generated.ts.
//
// Usage: pnpm --filter @yoyo/data scrape
// Output is committed to the repo; the script runs manually when the playlists change.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cleanTitle, parseEpisode, slugify, isSkippableTitle } from '../src/title-cleaning';

const PLAYLISTS: { id: string; level: 'beginner' | 'unresponsive' }[] = [
  { id: 'PL1zFX8tmxI9c_MhHM6Vu-pDlYffs5mL2C', level: 'beginner' },
  { id: 'PL1zFX8tmxI9c07kjmBvyF5rIRCWkE54gs', level: 'unresponsive' },
];

interface PlaylistVideo {
  ytId: string;
  rawTitle: string;
  lengthSeconds: number;
}

async function fetchPlaylist(playlistId: string): Promise<PlaylistVideo[]> {
  const url = `https://www.youtube.com/playlist?list=${playlistId}`;
  const res = await fetch(url, {
    headers: {
      'User-Agent':
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
      'Accept-Language': 'en-US,en;q=0.9',
    },
  });
  if (!res.ok) throw new Error(`Playlist ${playlistId}: HTTP ${res.status}`);
  const html = await res.text();
  const m = html.match(/var ytInitialData = (\{[\s\S]+?\});<\/script>/);
  if (!m) throw new Error(`Playlist ${playlistId}: ytInitialData not found`);
  const data = JSON.parse(m[1]!);

  const items =
    data?.contents?.twoColumnBrowseResultsRenderer?.tabs?.[0]?.tabRenderer?.content
      ?.sectionListRenderer?.contents?.[0]?.itemSectionRenderer?.contents?.[0]
      ?.playlistVideoListRenderer?.contents ?? [];

  const out: PlaylistVideo[] = [];
  for (const item of items) {
    const v = item.playlistVideoRenderer;
    if (!v) continue;
    const ytId: string | undefined = v.videoId;
    const rawTitle: string | undefined = v.title?.runs?.[0]?.text;
    const lengthSeconds = Number(v.lengthSeconds ?? 0);
    if (!ytId || !rawTitle || !Number.isFinite(lengthSeconds)) continue;
    out.push({ ytId, rawTitle, lengthSeconds });
  }
  return out;
}

interface TrickVideoEntry {
  id: string;
  ytId: string;
  slug: string;
  name: string;
  level: 'beginner' | 'unresponsive';
  playlistId: string;
  episode?: number;
  durationSec: number;
}

async function main(): Promise<void> {
  const all: TrickVideoEntry[] = [];
  const seenSlugs = new Map<string, number>();

  for (const { id: playlistId, level } of PLAYLISTS) {
    const videos = await fetchPlaylist(playlistId);
    for (const v of videos) {
      if (isSkippableTitle(v.rawTitle)) continue;
      const name = cleanTitle(v.rawTitle);
      if (!name) continue;
      let slug = slugify(name);
      if (!slug) continue;
      // De-dupe slugs if both playlists contain the same trick name.
      const seen = seenSlugs.get(slug) ?? 0;
      if (seen > 0) slug = `${slug}-${seen + 1}`;
      seenSlugs.set(slugify(name), seen + 1);

      const episode = parseEpisode(v.rawTitle);
      const entry: TrickVideoEntry = {
        id: v.ytId,
        ytId: v.ytId,
        slug,
        name,
        level,
        playlistId,
        durationSec: v.lengthSeconds,
      };
      if (episode !== undefined) entry.episode = episode;
      all.push(entry);
    }
  }

  const __filename = fileURLToPath(import.meta.url);
  const outPath = join(dirname(__filename), '..', 'src', 'generated', 'trick-videos.generated.ts');
  mkdirSync(dirname(outPath), { recursive: true });

  const body = `// AUTO-GENERATED by packages/data/scripts/scrape-playlists.ts.
// Do not edit by hand. Run \`pnpm scrape:videos\` to refresh.
import type { Trick, TrickLevel } from '../types';
import { ytThumbSet } from '../yt-thumb';

interface RawEntry {
  id: string;
  ytId: string;
  slug: string;
  name: string;
  level: TrickLevel;
  playlistId: string;
  episode?: number;
  durationSec: number;
}

const RAW: RawEntry[] = ${JSON.stringify(all, null, 2)};

export const TRICK_VIDEOS: Trick[] = RAW.map((v) => ({
  id: v.id,
  ytId: v.ytId,
  slug: v.slug,
  name: v.name,
  level: v.level,
  playlistId: v.playlistId,
  ...(v.episode !== undefined ? { episode: v.episode } : {}),
  durationSec: v.durationSec,
  thumbnails: ytThumbSet(v.ytId),
}));
`;

  writeFileSync(outPath, body, 'utf8');
  console.log(`Wrote ${all.length} entries to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
